### ISSUE TITLE
mouseKyc-fe : (Error) 'PORT' is not reconized !!

### ISSUE THREAD

**Issue by 4Maarifa** [norestlabs/mousekyc-fe#21]
### The mouseKyc-be folder
 @mdev0730   @gedanziger
I configured the project and I run it 
the result:
C:\Users\acer\coin-app\mousekyc-be (master -> origin)
λ npm start
norest-kyc-be@1.0.0 start C:\Users\acer\coin-app\mousekyc-be
nodemon src/app.js
[nodemon] 1.17.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node src/app.js`
cron started !
Created folder, /uploads
(node:8888) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Server listening at port 3000
(node:8888) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
demo admin created.

> I think it's ok

### The mouseKyc-fe folder
1.  I install  dependencies with  `npm install` in the  mousekyc-fe folder
2. after I run the project I get this error
C:\Users\acer\coin-app\mousekyc-fe>npm start
 nrl-kyc@0.1.0 start C:\Users\acer\coin-app\mousekyc-fe
 PORT=3006 react-app-rewired start

'PORT' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nrl-kyc@0.1.0 start: `PORT=3006 react-app-rewired start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nrl-kyc@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\acer\AppData\Roaming\npm-cache\_logs\2019-07-29T18_03_34_038Z-debug.log

C:\Users\acer\coin-app\mousekyc-fe>

**Comment by gedanziger** [comment]
hey @4Maarifa -> we normally run this on ubuntu 16.04/18.04 and OSX. We will try it out on windows and give some updated commands to run it

**Comment by 0xweb3builder** [comment]
Verified by c5ed5f78f156b604435e96d9e18675593e7bae0c

**Comment by gedanziger** [comment]
@4Maarifa - try pulling latest master now, it should run well on Windows
